// angular/src/app/components/buttons/read-btn/read-btn.ts
import { Component } from '@angular/core';
import { NgIcon, provideIcons } from "@ng-icons/core";
import { heroBookOpenSolid } from '@ng-icons/heroicons/solid';
import { ComicExtractorService } from '../../../service/comicExtractor.service';

@Component({
  selector: 'read-btn',
  imports: [NgIcon],
  providers: [
    provideIcons({
      heroBookOpenSolid
    })
  ],
  template: `
    <input
      type="file"
      name="comic-picker"
      id="comic-picker"
      accept="cbz, cbr"
      (change)="choseFile($event)"
    #hiddenfileinput>

    <button 
      class="kmk-read-btn"
      type="button"
      (click)="hiddenfileinput.click()">
      <ng-icon name="heroBookOpenSolid" size="20"/>
      Read
    </button>
  `,
  styleUrl: './read-btn.scss',
})
export class ReadBtn {
  private file: File | null = null;

  constructor(private comicExtractor: ComicExtractorService) { }

  async choseFile(event: any) {
    event.preventDefault();
    this.file = event.target?.files[0];

    try {
      if (this.file) {
        const comic: Comic = this.comicExtractor.extractInfos(this.file.name);
        console.log(comic);
        comic.cover = await this.comicExtractor.extractCover(this.file);

        console.log(comic);
      } else {
        alert('No file selected')
      }
    } catch (error) {
      console.log(error)
    }
  }
}

type Comic = {
  title: string;
  subtitle: string;
  edition: string;
  cover: Blob | undefined;
  key: string;
  reading: boolean;
}

// src/components/buttons/ReadBtn/index.tsx
import { BookOpenIcon } from "@heroicons/react/16/solid";
import { Button, Container } from "./style";
import { Title } from "../../base/Title";
import { useRef } from "react";
import { extractComicInfos } from "../../../service/utils/extractComicInfos";
import { extractComicCover } from "../../../service/utils/extractComicCover";
import { database } from "../../../service/db/db";
import type { ComicFile } from "../../../service/models/ComicFile";

export function ReadBtn() {
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleClick = () => {
    fileInputRef.current?.click();
  }

  const selectFile = async (evt: React.ChangeEvent<HTMLInputElement>) => {
    evt.preventDefault();

    try {
      const file = evt.target.files?.[0] as File;

      const comic = extractComicInfos(file?.name!);
      comic.cover = await extractComicCover(file!) ?? '';

      await database.comics.add(comic);

      const comicfile: ComicFile = {
        filename: file?.name ?? 'Not name',
        comicKey: comic.key,
        blob: file
      }

      await database.files.add(comicfile);
    } catch (error: any) {
      console.log(error);
      if (error.name === 'ConstraintError') {
        alert("Quadrinho já aberto");
        return;
      }
      
      alert("Erro ao extrair capa: Arquivo não suportado ou corrompido");
    }
  }

  return (
    <Container className="k-read-btn">
      <input
        type="file"
        ref={fileInputRef}
        onChange={selectFile}
        accept="cbz, cbr"
        style={{ display: 'none' }}
      />
      <Button onClick={handleClick}>
        <BookOpenIcon width={20} />
        <Title>Read</Title>
      </Button>
    </Container>
  )
}
