// src/components/ComicInfos/index.tsx
import { Subtitle } from "../base/Subtitle";
import { Title } from "../base/Title";
import { Infos } from "./style";

interface ComicInfosProps {
  title: string;
  subtitle: string;
  edition: string;
}

export function ComicInfos({
  title,
  subtitle,
  edition
}: ComicInfosProps) {
  return (
    <Infos>
      <div>
        <Title>{title}</Title>
        <Subtitle>{subtitle}</Subtitle>
      </div>
      <Subtitle>#{edition}</Subtitle>
    </Infos>
  )
}

// angular/src/app/components/misc/comic-infos/comic-infos.ts
import { Component, Input } from '@angular/core';
import { Title } from '../../base/title/title';
import { Subtitle } from '../../base/subtitle/subtitle';

@Component({
  selector: 'comic-infos',
  imports: [
    Title,
    Subtitle,
  ],
  templateUrl: './comic-infos.html',
  styleUrl: './comic-infos.scss',
})
export class ComicInfos {
  @Input() title: string = '';
  @Input() subtitle: string = '';
  @Input() edition: string = '';
}
